### ISSUE TITLE
btt.ahk (233) : ==> This line does not contain a recognized action. switch, O.BGCLGD

### ISSUE THREAD

**Issue by hygorrasec** [telppa/BeautifulToolTip#1]
>"D:\AutoHotkey\AutoHotkey.exe" /ErrorStdOut "E:\BeautifulToolTip\example 2.ahk"    
E:\BeautifulToolTip\Lib\btt.ahk (233) : ==> This line does not contain a recognized action.
Specifically: switch, O.BGCLGD
>Exit code: 2    Time: 0.141

**Comment by telppa** [comment]
ahk need v1.1.33.03
