### ISSUE TITLE
高分屏下界面过小

### ISSUE THREAD

**Issue by snomiao** [telppa/BeautifulToolTip#2]
![image](https://user-images.githubusercontent.com/7323030/115003649-97182a80-9ed8-11eb-80c3-48427e0a262a.png)
也许需要读一下每个屏幕的dpi设定……

**Comment by OnchiuLee** [comment]
> ![image](https://user-images.githubusercontent.com/7323030/115003649-97182a80-9ed8-11eb-80c3-48427e0a262a.png)
> 
> 也许需要读一下每个屏幕的dpi设定……

自己在字体计算处乘以dpi缩放比例

**Comment by telppa** [comment]
这是已知的。在字号那里乘以dpi系数就可以正常。没更新。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/BeautifulToolTip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 晚上6:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [telppa/BeautifulToolTip] 高分屏下界面过小 (#2)





  

 
也许需要读一下每个屏幕的dpi设定……
  
自己在字体计算处乘以dpi缩放比例

**Comment by telppa** [comment]
之前知道这个问题，没想好到底要不要默认去乘那个系数。
实际使用的话，因为可以传字号嘛，所以可以自己取一下dpi系数，然后传字号*dpi系数就好了。例如通常用12号字体，在300%缩放的屏幕下，就先传一个36号字体。

**Comment by snomiao** [comment]
如果需要另外传字号的话它和ahk 默认的  tooltip  行为就不 一样了

**Comment by telppa** [comment]
是的，这个也考虑过，但我忘了为啥没有立刻更新。可能当时想到了某种反例，才犹豫到底应不应该直接处理，也可能就是写别的去了，单纯忘了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snowstar ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 晚上7:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/BeautifulToolTip] 高分屏下界面过小 (#2)





 
如果需要另外传字号的话它和ahk 默认的  tooltip  行为就不 一样了

**Comment by OnchiuLee** [comment]
传毛线，可以dllcall获取系统默认字号大小大小直接乘dpi就好了

**Comment by telppa** [comment]
> 如果需要另外传字号的话它和ahk 默认的 tooltip 行为就不 一样了

想起原因了。因为不同系统（win7、win8、win10），获取多个显示器各自的dpi很麻烦，关键没测试条件了，所以被搁置了。

**Comment by telppa** [comment]
已修复。
