### ISSUE TITLE
Text being weirdly positioned/not centered

### ISSUE THREAD

**Issue by Animan8000** [telppa/BeautifulToolTip#4]
I used previously a [different](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=4777) ToolTip library and when I switched to this one I noticed a few inconsistencies, where some text looks weirdly positioned and not centered. Aside that the font (I think it's just the size and not necessarily the font itself) and ToolTip box size itself is different, the text in question has a bit too much free space above while below it's less free space. The text looks on the left side too close to the border while on the right there is sometimes a bit of space free depending on the string, and sometimes really close to the border in some strings. The template I use is:
```
DarkTheme := {TextColor:0xFFCFD1D4
, BackgroundColor:0xFF292A2D
, FontSize:14
, Margin:0
, Rounded:0}
```
Even if this *isn't a bug*, it would still be nice to have more control over **where** the text is positioned inside the ToolTip and to keep the amount of space in ToolTips on all corners equal or more consistent visually.

Thank you very much!

**Comment by telppa** [comment]
show me the screenshot.

**Comment by Animan8000** [comment]
I'm sorry for the late response! Here are a few small examples.

In this example the ")" character is too close to the right, to the border of the ToolTip
![ezgif-5-21b393ac0a](https://user-images.githubusercontent.com/30600651/151577995-79f42be2-7e38-41f2-a81c-97ac7fdf2ea8.gif)
In this example below it's not that extremly close to the border
![ToolTip](https://user-images.githubusercontent.com/30600651/151578051-28cb124b-355d-4966-b6e4-096b3e0f70f5.png)
From my experience the free space above the text in the ToolTip has like 1-2 pixels more free space below (I think it's probably 1 pixel difference only, not 100% sure at the moment)
![ToolTip2](https://user-images.githubusercontent.com/30600651/151578766-0dada377-9270-4137-afc6-8cc163afe4cf.png)
Another example of *there being more free space above the text and less below* (5 pixels free above the text, 4 pixels free below the text)
![image](https://user-images.githubusercontent.com/30600651/151579426-687d3c69-51b6-43b9-8a96-2907aa0de539.png)

**Comment by Animan8000** [comment]
Another example where a character (`z`) is too close to the right in my opinion
![image](https://user-images.githubusercontent.com/30600651/151580604-8ee43bc4-b118-4e61-9ba0-97565db1e1f8.png)

**Comment by telppa** [comment]
Unfortunately, this is probably not a bug, but a feature of GDI +. 

You can try to improve this by setting the `Margin` to non-zero value, or change the `Font`.

If you really need to fine-tune character positions, I recommend iseahound's [TextRender.](https://github.com/iseahound/TextRender)

**Comment by Animan8000** [comment]
Thanks! I'll look into that.
